### ISSUE TITLE
IndexError: Caught IndexError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by bjzhb666** [rasbt/cvpr2023#2]
![image](https://github.com/rasbt/cvpr2023/assets/71651717/718a0907-ad70-4a8b-843e-cadd5c74f7e3)
When I ran `python 01_pytorch-vit.py` or `python 00_pytorch-vit-random-init.py`, I got this error. How to solve it? Thanks!

**Comment by rasbt** [comment]
Hi there,
wow, this looks bizarre. It seems that the data loader may have gone out of control suggesting these very high index values. I've never seen something like this to be honest. 

Have you seen something like this before @awaelchli?

**Comment by awaelchli** [comment]
@bjzhb666 Did this happen at the beginning of training or sometime in the middle? Do `len(dataset)` and `len(dataloader)` return the expected values?

**Comment by bjzhb666** [comment]
Thanks for your quick reply. 
This happened at the beginning of training. I print `len(train_dataset)` and `len(train_dataloader)`, it returns 50000 and 703 (50000*0.9/64, where 64 is the batch size). They are all correct.

**Comment by rasbt** [comment]
Hm, this sounds normal to me. This error is so weird, I don't have any rational explanation for this.

**Comment by awaelchli** [comment]
Shouldn't matter, but can't hurt to try 😄:
1) create a fresh environment 2) reinstall torch

**Comment by DLwbm123** [comment]
Same error.

**Comment by rasbt** [comment]
I think I know where the error comes from. Since we are using regular dataloaders here (I used them for simplicity) instead of Lightning DataModules, the multiple GPUs try to download the dataset at the same time which can lead to corrupted files. I will update the files so that the data is downloaded separately first.

But what you can try is to delete your `data` directory, and then run it with 1 GPU and `Frabric(..., devices=1)`

If the error then still persists, then there is a different issue.
